# Generated by Django 2.2.5 on 2020-03-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file_no', models.CharField(max_length=25)),
                ('case_no', models.CharField(max_length=25)),
                ('court', models.CharField(max_length=100)),
                ('court_no', models.CharField(max_length=15)),
                ('male_suspect', models.CharField(max_length=150)),
                ('female_suspect', models.CharField(max_length=150)),
                ('male_underage_suspect', models.CharField(max_length=150)),
                ('female_underage_suspect', models.CharField(max_length=150)),
                ('assigned_to', models.CharField(max_length=150)),
                ('agency', models.CharField(choices=[('NS', 'NCS'), ('PL', 'Police'), ('DS', 'DSS'), ('OT', 'Others'), ('', 'Choose an Option')], default='', max_length=4)),
                ('date_of_request', models.DateTimeField(blank=True, null=True)),
                ('date_of_receipt', models.DateTimeField(blank=True, null=True)),
                ('st_deadline', models.DateTimeField(blank=True, null=True)),
                ('bail_granted', models.CharField(choices=[('YS', 'Yes'), ('NO', 'No')], max_length=2)),
                ('in_custody', models.CharField(choices=[('YS', 'Yes'), ('NO', 'No')], max_length=2)),
                ('date_of_remand', models.DateTimeField(blank=True, null=True)),
                ('place_of_remand', models.CharField(choices=[('NS', 'NCS'), ('PL', 'Police'), ('DS', 'DSS'), ('OT', 'Others'), ('', 'Choose an Option')], default='', max_length=4)),
                ('date_of_advive', models.DateTimeField(blank=True, null=True)),
                ('case_to_answer', models.CharField(choices=[('YS', 'Yes'), ('NO', 'No')], max_length=2)),
                ('entry_made_by', models.CharField(max_length=200)),
                ('update_made_by', models.CharField(max_length=200)),
            ],
        ),
    ]
