# Generated by Django 2.2.5 on 2020-06-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0003_auto_20200318_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttorneyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file_no', models.CharField(blank=True, max_length=25)),
                ('case_no', models.CharField(blank=True, max_length=25)),
                ('case_name', models.CharField(blank=True, max_length=25)),
                ('court', models.CharField(blank=True, max_length=15)),
                ('agency', models.CharField(choices=[('NS', 'NCS'), ('PL', 'Police'), ('DS', 'DSS'), ('OT', 'Others')], max_length=4)),
                ('no_defendant_male', models.CharField(max_length=150)),
                ('no_defendant_female', models.CharField(max_length=150)),
                ('no_underage_male', models.CharField(max_length=150)),
                ('no_underage_female', models.CharField(max_length=150)),
                ('no_pwds_male', models.CharField(max_length=150)),
                ('no_pwds_female', models.CharField(max_length=150)),
                ('counsel_name', models.CharField(max_length=150)),
                ('counsel_telephone', models.CharField(max_length=150)),
                ('adjourn_date', models.DateTimeField(blank=True, null=True)),
                ('reason_for_adjournment', models.CharField(choices=[('CDN', 'Court Did Not Sit'), ('AP', 'Absent Prosecution'), ('AC', 'Absent Defence Counsel'), ('AD', 'Absent Defendant'), ('PNR', 'Prosecution Not Ready'), ('PR', 'Request Prosecution'), ('RC', 'Request Counsel'), ('HD', 'Heard'), ('NHD', 'Not Heard')], max_length=4)),
                ('stage_of_proceedings', models.CharField(choices=[('ADA', 'Awaiting DPP Legal Advice'), ('AFC', 'Awaiting Filing of Charges/Information'), ('AR', 'Arraignment'), ('CT', 'Commencement of Trial'), ('TO', 'Trial Ongoing'), ('TWTO', 'Trial-within-Trial ongoing'), ('JG', 'Judgment and Sentencing')], max_length=4)),
                ('is_defendant_in_custody', models.CharField(choices=[('YS', 'Yes'), ('NO', 'No')], max_length=2)),
                ('has_bail_been_revoked', models.CharField(choices=[('YS', 'Yes'), ('NO', 'No')], max_length=2)),
                ('disposal', models.CharField(choices=[('CV', 'Conviction'), ('AC', 'Acquittal'), ('SO', 'Struck Out– Want Of Diligent Prosecution'), ('DS', 'Dismissal– No Case Submission')], max_length=2)),
                ('lead_counsel', models.CharField(max_length=200)),
                ('entry_made_by', models.CharField(max_length=200)),
                ('update_made_by', models.CharField(max_length=200)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='inventorymodel',
            old_name='date_of_advive',
            new_name='date_of_advice',
        ),
    ]
