# Generated by Django 2.2.5 on 2020-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0004_auto_20200607_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attorneymodel',
            old_name='update_made_by',
            new_name='entry_updated_by',
        ),
        migrations.AlterField(
            model_name='attorneymodel',
            name='counsel_telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attorneymodel',
            name='no_defendant_female',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attorneymodel',
            name='no_defendant_male',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attorneymodel',
            name='no_pwds_female',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attorneymodel',
            name='no_pwds_male',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attorneymodel',
            name='no_underage_female',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attorneymodel',
            name='no_underage_male',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='female_suspect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='female_underage_suspect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='male_suspect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='male_underage_suspect',
            field=models.IntegerField(),
        ),
    ]
