# Generated by Django 2.2.5 on 2020-06-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0006_auto_20200614_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_advice',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_receipt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_remand',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='st_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
