# Generated by Django 2.2.5 on 2020-06-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0007_auto_20200614_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorneymodel',
            name='adjourn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_advice',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_receipt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_remand',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='date_of_request',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='st_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
