# Generated by Django 2.2.5 on 2020-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0008_auto_20200614_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='entry_made_by',
            field=models.CharField(max_length=200),
        ),
    ]
