# Generated by Django 2.2.5 on 2020-06-21 20:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0010_auto_20200621_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorneymodel',
            name='counsel_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
